# Generated by Django 2.2 on 2019-04-08 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
