# Generated by Django 2.2 on 2019-04-03 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainService', '0002_make_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Songs',
        ),
    ]
