# Generated by Django 2.2 on 2019-04-04 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainService', '0003_delete_songs'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='make',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainService.Make'),
        ),
    ]
